## This is a personal config for Kometa. You can edit this file to your needs and be sure to fill in your personal keys 
## Overlays included for Movies in 4K, 1080p. Collections include IMDB, IMAX, DV, MCU, STar Wars. Star Trek, Harry Potter
## Overlays included for TV Shows in 4K. Collections inlude IMDB, Main Streaming Platforms and Major Networks.
##### Check your LIBRARY names in plex and copy them to the library names below. If your LIBRARY names are anything other than "Movies" and "TV Shows", change the names to match
##### ie. change the "Movies" to your movie library name and change "TV Shows" to your tv library name
## Fill in your plex IP under Settings Category along with plex token
## This version includes Notifiarr settings and webhook 
## TMDB and mdblist accounts are required for this scrypt to work. Fill in your apikeys where there are XXXXXXXXXXXXXXXXXXX

libraries:                       # This is called out once within the config.yml file
  Movies:  ################# THIS IS THE NAME OF YOUR "MOVIE" LIBRARY IN PLEX. IF YOUR MOVIE LIBRARY IS NAMED DIFFERENTLY THEN COPY THAT NAME HERE.
    report_path: config/missing/Movies_report.yml 
    collection_files:
      - default: basic                 # Creates Collections for New Episodes from last 7 days and Newly Released from past 90 days
      - default: imdb                  # Creates IMDB Collections for Popular and Top 250
        template_variables:
          name_popular: IMDb Popular Movies    #Option to rename the default "IMDb Popular" to a custom name
          use_lowest: false
          visible_home_top: true    #run once to create list to show when on the home screen, This is optional and can be turned off in Plex settings > Manage > Libaries > Manage Recommendations
          visible_home_popular: true    #run once to create list in home settings
    
    overlay_files:
      #- reset_overlays: plex      # reset overlays to plex or tmdb
      - remove_overlays: false     # Set this to true to remove all overlays
      - default: ratings                                  # Ratings with custom fonts matched to the style of the rating, font_size, and on the right in 'square' format
        template_variables:
          rating1: critic
          rating1_image: rt_tomato
          rating1_font: config/overlays/fonts/Adlib.ttf
          rating1_font_size: 63
          rating2: audience
          rating2_image: rt_popcorn
          rating2_font: config/overlays/fonts/Avenir_95_Black.ttf
          rating2_font_size: 70
          rating3: user
          rating3_image: imdb
          rating3_font: config/overlays/fonts/Impact.ttf
          rating3_font_size: 70
    operations:
      #mass_poster_update: plex                   #  Resets posters to tmdb or plex
      mass_user_rating_update: imdb           #  This operation will update the user rating in plex with imdb ratings information gathered through mdblist.com (mdblist config required)
          
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  missing_path: config/missing
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:
  run_order:                     # recommened run order keep operations first
  - operations
  - metadata
  - collections
  - overlays
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.11.2:32400    #fill in your IP address here ex 192.168.1.2 or 127.0.0.2 or whatever ip you use to access plex locally. 
  token: 2LCy_dAKmyTL8y7YP7y-
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
  db_cache: 1024
  verify_ssl: 
#notifiarr:
  #apikey: xxxxxxxxxxxxxxxxxxxxxxxxxx
tmdb:                            # REQUIRED for the script to run you need to create an account on tmdb.com https://kometa.wiki/en/latest/config/tmdb/
  apikey: aaa32e25c414b75099a7d0179cf3235e
  language: en
mdblist:                         # REQUIRED for the script to run you need to create an account on mdblist.com, you can create an account with trakt and link it. https://kometa.wiki/en/latest/config/mdblist/
  apikey: 514cjl2mnf40flm2mts4eah4c             
  cache_expiration: 60

  